# Generated by Django 4.2.1 on 2023-06-04 18:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fraction', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('day_of_week', models.IntegerField()),
                ('city_or_rural', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StreetAddress',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('street_name', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('purpose', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouteStreetAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.route')),
                ('street_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.streetaddress')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('vehicle', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.route')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('unique_identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('complaint_date', models.DateField()),
                ('modality', models.CharField(max_length=100)),
                ('recipient', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=100)),
                ('address_number', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.route')),
                ('street_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.streetaddress')),
            ],
        ),
    ]
